import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {calculateEstimate} from '../../site/simulator/src/calculator.js';
import {conciseEhimeAssumption,nonInclusionReason} from '../../site/simulator/src/subsidy-presentation.js';
const data=JSON.parse(await readFile(new URL('../../data/input/public-data.json',import.meta.url),'utf8'));
const standard=(municipalityCode,extra={})=>calculateEstimate({prefectureCode:'38',municipalityCode,equipmentPackage:'solar_plus_standard_battery',systemCapacityKw:4,batteryCapacityKwh:9.5,housingAge:'existing',monthlyElectricityBillYen:12000,...extra},data).scenarios.find(s=>s.scenario==='standard').subsidy_breakdown;
test('愛媛20市町38規則19採用を同期する',()=>{assert.equal(data.municipalities.filter(p=>p.prefecture_code==='38').length,20);const rows=data.diagnostic_subsidy_programs.filter(p=>p.id.startsWith('ehime-'));assert.equal(rows.length,38);assert.equal(rows.filter(p=>p.machine_rule==='kansai_municipal_formula').length,19);});
test('伊方通常の20万円控除・既存移住への切替と新築除外',()=>{for(const [housingAge,cap,amount] of [['new',4,56000],['new',4.5,68000],['new',9.5,189000],['new',10,200000],['existing',4,56000],['existing',4.5,363000],['existing',9.5,766000]])assert.equal(standard('38442',{housingAge,batteryCapacityKwh:cap}).municipality_amount_yen,amount);const n=standard('38442',{housingAge:'new'});assert.equal(n.excluded_programs.find(p=>p.id.includes('migration')).reason_code,'housing_age_not_applicable');assert.match(conciseEhimeAssumption({...n.included_programs.find(p=>p.id.startsWith('ehime')),included:true}),/他の補助金と20万円を一度だけ/);});
test('大洲・四国中央も4から4.5kWhで最低費用境界を跨ぐ',()=>{for(const [code,at4] of [['38207',48000],['38213',100000]]){assert.equal(standard(code,{batteryCapacityKwh:4}).municipality_amount_yen,at4);assert.equal(standard(code,{batteryCapacityKwh:4.5}).municipality_amount_yen,363000);}});
test('愛南は移住と通常Bの控除併用，新築では移住非算入',()=>{const b=standard('38506');assert.equal(b.municipality_amount_yen,894000);assert.equal(b.included_programs.find(p=>p.id==='ehime-38506-energy-2026').amount_yen,128000);assert.equal(b.included_programs.find(p=>p.id.includes('migration')).amount_yen,766000);assert.equal(standard('38506',{housingAge:'new'}).municipality_amount_yen,200000);const row=b.included_programs.find(p=>p.id.includes('migration'));assert.match(conciseEhimeAssumption({...row,included:true}),/県外移住.*空き家バンク.*適格性を確認済みではありません.*取得費.*通常設備補助側/);});
test('移住前提・工事費・未確認の個別留保を残す',()=>{for(const code of ['38207','38213','38442'])assert.match(conciseEhimeAssumption({id:`ehime-${code}-migration_battery-2026`,included:true}),/50万円以上.*部分配賦は未対応/);assert.match(conciseEhimeAssumption({id:'ehime-38401-energy-2026',included:true}),/設置工事費の対象性は未確認/);assert.match(conciseEhimeAssumption({id:'ehime-38213-energy-2026',included:true}),/最終端数処理は未確認/);assert.match(nonInclusionReason(standard('38202').excluded_programs.find(p=>p.id.includes('energy_closed'))),/受付が終了/);});

test('移住改修の50万円未達は詳細未確認候補ではなく費用条件外である',()=>{for(const code of ['38207','38213','38442']){const b=standard(code,{batteryCapacityKwh:4});assert.ok(!b.candidate_programs.some(p=>p.id.includes('migration_battery')));const row=b.excluded_programs.find(p=>p.id.includes('migration_battery'));assert.equal(row.reason_code,'eligible_cost_below_minimum');assert.match(nonInclusionReason(row),/対象費用が制度の最低額に届かない/);assert.doesNotMatch(nonInclusionReason(row),/未確認/);}});
