import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {calculateEstimate} from '../../site/simulator/src/calculator.js';
const data=JSON.parse(await readFile(new URL('../../data/input/public-data.json',import.meta.url),'utf8'));
const standard=(code,systemCapacityKw=4)=>calculateEstimate({prefectureCode:'15',municipalityCode:code,equipmentPackage:'solar_plus_standard_battery',systemCapacityKw,batteryCapacityKwh:9.5,housingAge:'existing',monthlyElectricityBillYen:12000},data).scenarios.find(s=>s.scenario==='standard').subsidy_breakdown;
test('新潟30自治体24制度と9代表額を受け入れる',()=>{assert.equal(data.municipalities.filter(m=>m.prefecture_code==='15').length,30);assert.equal(data.diagnostic_subsidy_programs.filter(p=>p.prefecture_code==='15'&&p.government_level==='municipality').length,24);for(const[c,n]of [['15100',175000],['15208',300000],['15210',400000],['15211',380000],['15212',280000],['15216',255000],['15224',445000],['15225',400000],['15461',200000]])assert.equal(standard(c).municipality_amount_yen,n,c);});
test('新潟のPV枝採用・受付継続仮定・限定探索終了を区別する',()=>{for(const[c,id]of [['15210','tokamachi-renewable-energy-2026'],['15212','murakami-residential-solar-2026']]){const p=standard(c).included_programs.find(p=>p.id===id);assert.equal(p.component_amounts_yen.battery??0,0);assert.match(p.calculation_assumptions.join(' '),/蓄電池枝.*算入しない/);}const pending=standard('15223').included_programs.find(p=>p.id==='agano-residential-solar-2026');assert.ok(pending);assert.ok(pending.amount_yen>0);assert.equal(pending.application_status,'accepting');assert.match(pending.calculation_assumptions.join(' '),/受付継続を仮定/);assert.equal(data.municipalities.find(m=>m.municipality_code==='15581').program_status,'searched_not_found');});
test('佐渡は独立②対象の現行UI下限3kWで算入する',()=>{const r=standard('15224',3);assert.ok(r.municipality_amount_yen>0);assert.ok(r.included_programs.some(p=>p.id==='sado-clean-energy-2026'));});
