import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {diagnosticSubsidy} from '../../site/simulator/src/diagnostic-subsidy.js';
import {calculateEstimate} from '../../site/simulator/src/calculator.js';
const data=JSON.parse(await readFile(new URL('../../data/input/public-data.json',import.meta.url),'utf8'));
const standard=(code,equipmentPackage='solar_plus_standard_battery',batteryCapacityKwh=9.5)=>calculateEstimate({prefectureCode:'30',municipalityCode:code,equipmentPackage,systemCapacityKw:4,batteryCapacityKwh,housingAge:'existing',monthlyElectricityBillYen:12000},data).scenarios.find(s=>s.scenario==='standard').subsidy_breakdown;
test('和歌山30自治体と代表額・設備枝・蓄電池成分境界を保持する',()=>{assert.equal(data.municipalities.filter(m=>m.prefecture_code==='30').length,30);assert.equal(standard('30201','solar_only').municipality_amount_yen,6000);for(const[b,n]of [[9.5,200000],[4,200000]])assert.equal(standard('30366','solar_plus_standard_battery',b).municipality_amount_yen,n);for(const[b,n]of [[9.5,280000],[4,241000]])assert.equal(standard('30392','solar_plus_standard_battery',b).municipality_amount_yen,n);assert.equal(standard('30392','solar_only').municipality_amount_yen,0);});
test('和歌山の非現金と非FIT・受付終了及びHTTP出典を保持する',()=>{const city=standard('30201','solar_only');assert.match(city.included_programs.find(p=>p.id==='wakayama-solar-credit-membership-2026').calculation_assumptions.join(' '),/QUOカード.*非現金/);assert.ok(standard('30201').excluded_programs.some(p=>p.reason_code==='application_closed'));assert.equal(standard('30366').excluded_programs.find(p=>p.id==='aridagawa-residential-renewable-nonfit-2026').reason_code,'sale_path_not_applicable');for(const p of data.diagnostic_subsidy_programs.filter(p=>p.prefecture_code==='30'&&p.official_urls[0].startsWith('http:'))){const r=standard(p.municipality_code);assert.equal([...r.included_programs,...r.excluded_programs,...r.candidate_programs].find(r=>r.id===p.id).official_url,p.official_urls[0]);}});

test('有田川の4kWh未満は太陽光成分を維持する',()=>{const r=diagnosticSubsidy(data.diagnostic_subsidy_programs,{prefectureCode:'30',municipalityCode:'30366',housingAge:'existing',equipmentPackage:'solar_plus_standard_battery',capacityKw:4,batteryCapacityKwh:3.999,solarCost:1324400,batteryCost:483879,batteryEquipmentCost:300000},true);assert.equal(r.municipality_amount_yen,120000);});
